\documentclass[a4paper,10pt]{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}                       % for mathematical features 
\usepackage[left=2.5cm,top=3cm,bottom=3cm,right=2.5cm]{geometry}   % text margins
\usepackage{booktabs}                      % for booktabs in print(xtable)).
\usepackage{authblk}                       % for footnote style author/affiliation
\usepackage{amssymb}
\usepackage{amsthm}
% LaTeX package for captions customization:
\usepackage[margin=10pt,font=small,labelfont=bf,format=hang]{caption}
\usepackage{hyperref}                      % Hyperlinks and \url{}
\hypersetup{
    colorlinks=true, % Enable colored text for links instead of drawing boxes
    linkcolor=blue,  % Color for internal document links (e.g., sections, equations, figures, tables)
    citecolor=blue,  % Color for bibliographic citation links (e.g., \cite{})
    urlcolor=blue    % Color for external web URLs (e.g., \url{})
}


\begin{document}
\title{Statistics in Health Sciences - Assignment 1}
\author{G05: Judit Félelz Guerrero (17048330), Lídia Abio Rojo (1705251), Catalina Mascaró Català (1708159), Elia Campos Villaro (1703842)}
\date{28th October 2026}



\maketitle

\newpage

\section{Introduction}
The aim of this assignment is to apply the framework proposed by Basagaña et al. to the data set copd in the file copd redux.RData. Data copd is a subset of 45 variables of the original data analyzed in the cited paper.


\section{Analysis}

\subsection{Description of missingness}

Provide the same missingness description than in the original analysis. Specifically, reproduce the following text that is shown in the original paper:

\begin{quotation}
``The subset used here included \textcolor{red}{342} participants and \textcolor{red}{85} variables. The range of missing data in the different variables went from \textcolor{red}{0\%} to \textcolor{red}{47.7\%}, with \textcolor{red}{68.2\%} of the variables having less than 5\% of the data missing. Only \textcolor{red}{13.7\%} of the participants had complete data on all \textcolor{red}{85} variables. Overall, \textcolor{red}{5.9\%} of the information was missing; that is, \textcolor{red}{5.9\%} of the total of \textcolor{red}{29,070} cells (\textcolor{red}{$85 \times 342 = 29,070$}) had missing data.''
\end{quotation}

Instructions:

\begin{itemize}
    \item Note that, since you are working with a subset of the original data set, red numbers above are not expected to be the same than in your results.
    
    \item In your \textbf{\texttt{Rnw}} document, the text above must be able to automatically update all red numbers in the case of changing the values of \textbf{\texttt{copd}}. I.e., if data change, then all red numbers must also automatically update accordingly in your \textbf{\texttt{pdf}} when compiling your \textbf{\texttt{Rnw}}. As a hint, you can follow this procedure:
    
    \begin{enumerate}
        \item For each red number, create an \textsf{R} object, which will depend on data and gives the desired quantity (i.e., if data change, the value in the object changes accordingly),
        \item To force rounding a quantity to a given decimal precision, you can use \texttt{sprintf()} (as seen in Exercise 0). Do not use \texttt{round()},
        \item To get the thousands comma separator as in ``29,070'', you can use \texttt{prettyNum()},
        \item Once you have an \textsf{R} object for each red number formatted as desired, use \texttt{\textbackslash Sexpr\{\}} to insert each of them inline in \LaTeX{} (as seen in Exercise 0).
    \end{enumerate}
\end{itemize}

<<libraries, include=FALSE>>=
### libraries related to knit:
library(knitr)
library(xtable)     # to create nice LaTeX tables
library(mice)
library(miclust)
library(miceadds)
@


<<setting, include=FALSE, purl=FALSE>>=
### output options (there are a lot..):
options(width = 90, # max. width, in characters, of the R output. Default is 80.
        scipen = 4)  # to avoid printing inline R output numbers in scientific
# notation if they are lower than 10^4


### set global chunk options. They apply to all chuncks except to those in which you set otherwise
opts_chunk$set(echo = TRUE,         # show R input code
               eval = TRUE,         # show R output
               message = TRUE,       # set to FALSE to avoid nuisance messages (be careful!)         
               warning = TRUE,       # set to FALSE to avoid nuisance messages (be careful!)         
               size = "footnotesize", # set the R output and output font size 
               cache = TRUE,        # useful for computationally costly chunks (be careful if set to TRUE!)
               prompt = TRUE)
@


<<data, include=FALSE>>=
### Loading data from "copd_redux.RData" file in the working directory:
load("./copd_redux.RData")
@

<<missingness>>=
n_obs <- nrow(copd) # Number of participants
n_vars <- ncol(copd) # Number of variables
nans <- 100*colMeans(is.na(copd)) # Percentage of missing data by variable
min_nan <- sprintf("%.2g", min(nans)) # MIRAR # Lower percentage
max_nan <- sprintf("%.2g", max(nans)) # Upper percentage

# Vairables with less than 5% of data missing (percentage)
less_5 <- sprintf("%.2g", 100*length(nans[nans<5])/n_vars) 

# Percentage of complete cases
comp_cases <- sprintf("%.2g", 100*mean(complete.cases(copd)))

# Percentage of missing data
miss_total <-  sprintf("%.2g", 100*mean(is.na(copd)))

# Total cells observed (variables*observations)
total_cells = prettyNum(n_obs*n_vars, big.mark = ",", decimal.mark = ".")
@

“The subset used here included \Sexpr{n_obs} participants and \Sexpr{n_vars} variables. The range of missing data in the different variables went from \Sexpr{min_nan}\% to \Sexpr{max_nan}\%, with \Sexpr{less_5}\% of the variables having less than 5\% of the data missing. Only \Sexpr{comp_cases}\% of the participants had complete data on all \Sexpr{n_vars} variables. Overall, \Sexpr{miss_total}\% of the information was missing; that is, \Sexpr{miss_total}\% of the total of \Sexpr{total_cells} cells (\Sexpr{n_vars} × \Sexpr{n_obs} = \Sexpr{total_cells}) had missing data.”

\subsection{Multiple imputation}

Apply multiple imputation to copd data using 100 imputations. Explain in a reasoned manner how you decided to set the values of the arguments \texttt{method} and \texttt{predictorMatrix} when using the \texttt{mice()} function. Show your code.

<<imputation_ini>>=
# Display of default imputation methods for each variable
ini <- mice(copd, maxit=0)
ini
@

We can see that the mice package suggest imputing initialy with de mean for continuous variables and with a logistic regression for binary ones. Further research on the dataset has shown that the variables have no deterministic relation. So we do not change the imputation methods. We have a variable (\texttt{id}) that don't have any role in the imputation process, so we change \texttt{predictorMatrix} and \texttt{methods} acording to that.

<<imputation_parameters>>=
# Change in parameters
meth <- ini$method
pred <- ini$predictorMatrix

meth["id"] <- "" # do not impute "id"
pred["id", ] <- 0 # we don't want "id" to be imputed
pred[, "id"] <- 0 # we don't want "id" to be predictor
@

<<imputation>>=
# Imputation of 100 datasets
M <- 2 # Number of imputations for each missing value
imp <- mice(data = copd, 
            m = M, 
            method = meth, 
            predictorMatrix = pred,
            maxit = 20,
            printFlag = FALSE,
            seed = 666)
# imp$imp (output llarg)
head(imp$imp)
@


\subsection{Integration of multiple imputation in cluster analysis}

Reproduce the original analysis in the paper using the miclust package to integrate multiple
imputation in the cluster analysis. Apply the proposed framework using the same setting
than in the original analysis. To do that, follow these steps:

\begin{enumerate}
  \item Read the help of the \texttt{getdata()} function in the \texttt{miclust} package. Then, accordingly, 
  create a \textit{list} of \textit{data.frames} and pass it to the \texttt{getdata()} function. Give a detailed
  explanation of the data processing you did to get that \textit{list}. Show your code.
  
  \item Use the \texttt{miclust()} function to perform the integration of missing data in cluster
  analysis using the same settings as in the original analysis. Show your code and
  explain how and why you set all arguments in the \texttt{miclust()} function.

\end{enumerate}





\end{document}