\documentclass[a4paper,10pt]{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}                       % for mathematical features 
\usepackage[left=2.5cm,top=3cm,bottom=3cm,right=2.5cm]{geometry}   % text margins
\usepackage{booktabs}                      % for booktabs in print(xtable)).
\usepackage{authblk}                       % for footnote style author/affiliation
\usepackage{amssymb}
\usepackage{amsthm}
% LaTeX package for captions customization:
\usepackage[margin=10pt,font=small,labelfont=bf,format=hang]{caption}
\usepackage{hyperref}                      % Hyperlinks and \url{}
\hypersetup{
    colorlinks=true, % Enable colored text for links instead of drawing boxes
    linkcolor=blue,  % Color for internal document links (e.g., sections, equations, figures, tables)
    citecolor=blue,  % Color for bibliographic citation links (e.g., \cite{})
    urlcolor=blue    % Color for external web URLs (e.g., \url{})
}


\begin{document}
\title{Statistics in Health Sciences - Assignment 1}
\author{G05: Judit Félelz Guerrero (17048330), Lídia Abio Rojo (1705251), Catalina Mascaró Català (1708159), Elia Campos Villaro (1703842)}
\date{28th October 2026}



\maketitle

\newpage

\section{Introduction}
The aim of this assignment is to apply the framework proposed by Basagaña et al. to the data set copd in the file copd redux.RData. Data copd is a subset of 45 variables of the original data analyzed in the cited pape.


\section{Analysis}

\subsection{Description of missingness}

Provide the same missingness description than in the original analysis. Specifically, reproduce the following text that is shown in the original paper:

\begin{quotation}
``The subset used here included \textcolor{red}{342} participants and \textcolor{red}{85} variables. The range of missing data in the different variables went from \textcolor{red}{0\%} to \textcolor{red}{47.7\%}, with \textcolor{red}{68.2\%} of the variables having less than 5\% of the data missing. Only \textcolor{red}{13.7\%} of the participants had complete data on all \textcolor{red}{85} variables. Overall, \textcolor{red}{5.9\%} of the information was missing; that is, \textcolor{red}{5.9\%} of the total of \textcolor{red}{29,070} cells (\textcolor{red}{$85 \times 342 = 29,070$}) had missing data.''
\end{quotation}

Instructions:

\begin{itemize}
    \item Note that, since you are working with a subset of the original data set, red numbers above are not expected to be the same than in your results.
    
    \item In your \textbf{\texttt{Rnw}} document, the text above must be able to automatically update all red numbers in the case of changing the values of \textbf{\texttt{copd}}. I.e., if data change, then all red numbers must also automatically update accordingly in your \textbf{\texttt{pdf}} when compiling your \textbf{\texttt{Rnw}}. As a hint, you can follow this procedure:
    
    \begin{enumerate}
        \item For each red number, create an \textsf{R} object, which will depend on data and gives the desired quantity (i.e., if data change, the value in the object changes accordingly),
        \item To force rounding a quantity to a given decimal precision, you can use \texttt{sprintf()} (as seen in Exercise 0). Do not use \texttt{round()},
        \item To get the thousands comma separator as in ``29,070'', you can use \texttt{prettyNum()},
        \item Once you have an \textsf{R} object for each red number formatted as desired, use \texttt{\textbackslash Sexpr\{\}} to insert each of them inline in \LaTeX{} (as seen in Exercise 0).
    \end{enumerate}
\end{itemize}

<<libraries, include=FALSE>>=
### libraries related to knit:
library(knitr)
library(xtable)     # to create nice LaTeX tables
@


<<setting, include=FALSE, purl=FALSE>>=
### output options (there are a lot..):
options(width = 90, # max. width, in characters, of the R output. Default is 80.
        scipen = 4)  # to avoid printing inline R output numbers in scientific
# notation if they are lower than 10^4


### set global chunk options. They apply to all chuncks except to those in which you set otherwise
opts_chunk$set(echo = TRUE,         # show R input code
               eval = TRUE,         # show R output
               message = TRUE,       # set to FALSE to avoid nuisance messages (be careful!)         
               warning = TRUE,       # set to FALSE to avoid nuisance messages (be careful!)         
               size = "footnotesize", # set the R output and output font size 
               cache = FALSE,        # useful for computationally costly chunks (be careful if set to TRUE!)
               prompt = TRUE)
@


<<data, include=FALSE>>=
### Loading data from "copd_redux.RData" file in the working directory:
load("./copd_redux.RData")
@

<<missingness>>=
n_obs <- nrow(copd)
n_vars <- ncol(copd)
nans <- 100*colMeans(is.na(copd))
min_nan <- sprintf("%.2g", min(nans)) # MIRAR
max_nan <- sprintf("%.2g", max(nans))
less_5 <- sprintf("%.2g", 100*length(nans[nans<5])/n_vars) 
comp_cases <- sprintf("%.2g", 100*mean(complete.cases(copd)))
miss_total <-  sprintf("%.2g", 100*mean(is.na(copd)))
total_cells = prettyNum(n_obs*n_vars, big.mark = ",", decimal.mark = ".")
@

“The subset used here included \Sexpr{n_obs} participants and \Sexpr{n_vars} variables. The range of missing data in the different variables went from \Sexpr{min_nan}\% to \Sexpr{max_nan}\%, with \Sexpr{less_5}\% of the variables having less than 5\% of the data missing. Only \Sexpr{comp_cases}\% of the participants had complete data on all \Sexpr{n_vars} variables. Overall, \Sexpr{miss_total}\% of the information was missing; that is, \Sexpr{miss_total}\% of the total of \Sexpr{total_cells} cells (\Sexpr{n_vars} × \Sexpr{n_obs} = \Sexpr{total_cells}) had missing data.”

\end{document}